# RFID Object Localization 
# Service operations
# 
# REQUEST
# action    operation to be performed: 'list','find','accurate_find'
# payload   options for the requested action:
#                - 'list':           'objects' , 'locations' or 'sublocations'
#                                    When listing sublocations, areas without sublocations are also reported.
#                - 'find':           one of the objects given by a previous 'list' 'objects'. first location has probability -1, meaning it was last place seen/detected
#                - 'accurate_find':  as find, but answer will be using sublocations. Probalities here are relative to that location.
#				     A sublocation is an smaller area inside a bigger one.
#
# RESPONSE
# response  String, coma separated on success or empty on fail
#            examples: 'list' 'objects'         -> 'remote,glasses,pillbox,wallet,umbrella'
#                      'list' 'locations'       -> 'kitchen,livingroom,bedroom,bathroom'
#                      'list' 'sublocations'    -> 'kitchen - fridge,kitchen - cook,livingroom - sofas,livingroom - tv,bedroom,bathroom'
#                      'find' 'remote'          -> 'livingroom,-1,kitchen,60.02,livingroom,20.48,bedroom,14.31,bathroom,5.69'
#                      'accurate_find' 'remote' -> 'fridge,54.40,cook,45.60'
#                      'find' 'pink'            -> ''             wasOk == False   feedback='object not in system'
# wasOk     boolean indicating successful action
# feedback  extra information on error (if possible)


string    action
string    payload
---
string    response
bool      wasOk
string    feedback
